import * as React from "react"
const { createContext, useContext, useState } = React

// Translation data
const translations = {
  vi: {
    // Common UI elements
    "Select a role": "Chọn vai trò",
    "Search roles...": "Tìm kiếm vai trò...",
    "Select a language": "Chọn ngôn ngữ",
    "Search languages...": "Tìm kiếm ngôn ngữ...",
    "Select a currency": "Chọn tiền tệ",
    "Search currencies...": "Tìm kiếm tiền tệ...",
    "Select a channel": "Chọn kênh",
    "Search channels...": "Tìm kiếm kênh...",
    "Deleted successfully": "Xóa thành công",
    "Failed to delete": "Xóa thất bại",
    Save: "Lưu",
    Cancel: "Hủy",
    Delete: "Xóa",
    Edit: "Chỉnh sửa",
    Create: "Tạo",
    Update: "Cập nhật",
    Search: "Tìm kiếm",
    Filter: "Lọc",
    Sort: "Sắp xếp",
    "Loading...": "Đang tải...",
    Error: "Lỗi",
    Success: "Thành công",
    Warning: "Cảnh báo",
    Info: "Thông tin",
    Yes: "Có",
    No: "Không",
    OK: "OK",
    Close: "Đóng",
    Back: "Quay lại",
    Next: "Tiếp theo",
    Previous: "Trước",
    Submit: "Gửi",
    Reset: "Đặt lại",
    Clear: "Xóa",
    Add: "Thêm",
    Remove: "Xóa",
    View: "Xem",
    Details: "Chi tiết",
    Settings: "Cài đặt",
    Profile: "Hồ sơ",
    Logout: "Đăng xuất",
    Login: "Đăng nhập",
    Register: "Đăng ký",
    Password: "Mật khẩu",
    Username: "Tên người dùng",
    Email: "Email",
    Name: "Tên",
    Description: "Mô tả",
    Title: "Tiêu đề",
    Status: "Trạng thái",
    Active: "Hoạt động",
    Inactive: "Không hoạt động",
    Enabled: "Đã bật",
    Disabled: "Đã tắt",
    Public: "Công khai",
    Private: "Riêng tư",
    Draft: "Bản nháp",
    Published: "Đã xuất bản",
    Pending: "Đang chờ",
    Approved: "Đã phê duyệt",
    Rejected: "Đã từ chối",
    Completed: "Hoàn thành",
    "In Progress": "Đang thực hiện",
    Failed: "Thất bại",
    Created: "Đã tạo",
    Updated: "Đã cập nhật",
    Deleted: "Đã xóa",
    "Created at": "Tạo lúc",
    "Updated at": "Cập nhật lúc",
    Actions: "Hành động",
    Options: "Tùy chọn",
    Configuration: "Cấu hình",
    General: "Chung",
    Advanced: "Nâng cao",
    Basic: "Cơ bản",
    Required: "Bắt buộc",
    Optional: "Tùy chọn",
    Default: "Mặc định",
    Custom: "Tùy chỉnh",
    All: "Tất cả",
    None: "Không có",
    "Select All": "Chọn tất cả",
    "Deselect All": "Bỏ chọn tất cả",
    Select: "Chọn",
    Unselect: "Bỏ chọn",
    Choose: "Chọn",
    Browse: "Duyệt",
    Upload: "Tải lên",
    Download: "Tải xuống",
    Export: "Xuất",
    Import: "Nhập",
    Print: "In",
    Copy: "Sao chép",
    Paste: "Dán",
    Cut: "Cắt",
    Undo: "Hoàn tác",
    Redo: "Làm lại",
    Refresh: "Làm mới",
    Reload: "Tải lại",
    Restart: "Khởi động lại",
    Start: "Bắt đầu",
    Stop: "Dừng",
    Pause: "Tạm dừng",
    Resume: "Tiếp tục",
    Continue: "Tiếp tục",
    Finish: "Kết thúc",
    Complete: "Hoàn thành",
    Confirm: "Xác nhận",
    Verify: "Xác minh",
    Validate: "Xác thực",
    Check: "Kiểm tra",
    Test: "Kiểm tra",
    Preview: "Xem trước",
    Review: "Xem xét",
    Approve: "Phê duyệt",
    Reject: "Từ chối",
    Accept: "Chấp nhận",
    Decline: "Từ chối",
    Enable: "Bật",
    Disable: "Tắt",
    Activate: "Kích hoạt",
    Deactivate: "Hủy kích hoạt",
    Install: "Cài đặt",
    Uninstall: "Gỡ cài đặt",
    Upgrade: "Nâng cấp",
    Downgrade: "Hạ cấp",
    Migrate: "Di chuyển",
    Backup: "Sao lưu",
    Restore: "Khôi phục",
    Sync: "Đồng bộ",
    Connect: "Kết nối",
    Disconnect: "Ngắt kết nối",
    Link: "Liên kết",
    Unlink: "Hủy liên kết",
    Share: "Chia sẻ",
    Send: "Gửi",
    Receive: "Nhận",
    Get: "Lấy",
    Set: "Đặt",
    Change: "Thay đổi",
    Modify: "Sửa đổi",
    Adjust: "Điều chỉnh",
    Configure: "Cấu hình",
    Setup: "Thiết lập",
    Initialize: "Khởi tạo",
    Empty: "Trống",
    Full: "Đầy",
    Available: "Có sẵn",
    Unavailable: "Không có sẵn",
    Online: "Trực tuyến",
    Offline: "Ngoại tuyến",
    Connected: "Đã kết nối",
    Disconnected: "Đã ngắt kết nối",
    Open: "Mở",
    Show: "Hiển thị",
    Hide: "Ẩn",
    Display: "Hiển thị",
    Visible: "Hiển thị",
    Hidden: "Ẩn",
    Expand: "Mở rộng",
    Collapse: "Thu gọn",
    Minimize: "Thu nhỏ",
    Maximize: "Phóng to",
    Fullscreen: "Toàn màn hình",
    Window: "Cửa sổ",
    Tab: "Tab",
    Page: "Trang",
    Section: "Phần",
    Category: "Danh mục",
    Group: "Nhóm",
    Item: "Mục",
    Element: "Phần tử",
    Component: "Thành phần",
    Module: "Mô-đun",
    Plugin: "Plugin",
    Extension: "Tiện ích mở rộng",
    Feature: "Tính năng",
    Function: "Chức năng",
    Service: "Dịch vụ",
    API: "API",
    Database: "Cơ sở dữ liệu",
    Server: "Máy chủ",
    Client: "Máy khách",
    User: "Người dùng",
    Admin: "Quản trị viên",
    Guest: "Khách",
    Member: "Thành viên",
    Customer: "Khách hàng",
    Vendor: "Nhà cung cấp",
    Seller: "Người bán",
    Buyer: "Người mua",
    Order: "Đơn hàng",
    Product: "Sản phẩm",
    Payment: "Thanh toán",
    Shipping: "Vận chuyển",
    Delivery: "Giao hàng",
    Address: "Địa chỉ",
    Location: "Vị trí",
    Country: "Quốc gia",
    State: "Trạng thái",
    City: "Thành phố",
    "Zip Code": "Mã bưu điện",
    Phone: "Điện thoại",
    Mobile: "Di động",
    Website: "Trang web",
    URL: "URL",
    Image: "Hình ảnh",
    Photo: "Ảnh",
    Picture: "Hình ảnh",
    File: "Tệp",
    Document: "Tài liệu",
    Folder: "Thư mục",
    Directory: "Thư mục",
    Path: "Đường dẫn",
    Size: "Kích thước",
    Type: "Loại",
    Format: "Định dạng",
    Version: "Phiên bản",
    Date: "Ngày",
    Time: "Thời gian",
    Duration: "Thời lượng",
    Price: "Giá",
    Cost: "Chi phí",
    Amount: "Số tiền",
    Total: "Tổng",
    Subtotal: "Tổng phụ",
    Tax: "Thuế",
    Discount: "Giảm giá",
    Quantity: "Số lượng",
    Weight: "Trọng lượng",
    Length: "Chiều dài",
    Width: "Chiều rộng",
    Height: "Chiều cao",
    Volume: "Thể tích",
    Area: "Diện tích",
    Distance: "Khoảng cách",
    Speed: "Tốc độ",
    Rate: "Tỷ lệ",
    Percentage: "Phần trăm",
    Ratio: "Tỷ lệ",
    Average: "Trung bình",
    Minimum: "Tối thiểu",
    Maximum: "Tối đa",
    Range: "Phạm vi",
    Limit: "Giới hạn",
    Threshold: "Ngưỡng",
    Target: "Mục tiêu",
    Goal: "Mục tiêu",
    Objective: "Mục tiêu",
    Purpose: "Mục đích",
    Reason: "Lý do",
    Cause: "Nguyên nhân",
    Effect: "Hiệu ứng",
    Result: "Kết quả",
    Outcome: "Kết quả",
    Impact: "Tác động",
    Influence: "Ảnh hưởng",
    Benefit: "Lợi ích",
    Advantage: "Ưu điểm",
    Disadvantage: "Nhược điểm",
    Problem: "Vấn đề",
    Issue: "Vấn đề",
    Challenge: "Thách thức",
    Difficulty: "Khó khăn",
    Solution: "Giải pháp",
    Answer: "Câu trả lời",
    Response: "Phản hồi",
    Reply: "Trả lời",
    Feedback: "Phản hồi",
    Comment: "Bình luận",
    Note: "Ghi chú",
    Remark: "Nhận xét",
    Observation: "Quan sát",
    Analysis: "Phân tích",
    Report: "Báo cáo",
    Summary: "Tóm tắt",
    Overview: "Tổng quan",
    Introduction: "Giới thiệu",
    Conclusion: "Kết luận",
    Recommendation: "Khuyến nghị",
    Suggestion: "Đề xuất",
    Proposal: "Đề xuất",
    Plan: "Kế hoạch",
    Strategy: "Chiến lược",
    Method: "Phương pháp",
    Approach: "Cách tiếp cận",
    Technique: "Kỹ thuật",
    Process: "Quy trình",
    Procedure: "Thủ tục",
    Step: "Bước",
    Stage: "Giai đoạn",
    Phase: "Giai đoạn",
    Level: "Cấp độ",
    Grade: "Cấp độ",
    Rank: "Xếp hạng",
    Position: "Vị trí",
    Role: "Vai trò",
    Job: "Công việc",
    Task: "Nhiệm vụ",
    Assignment: "Phân công",
    Project: "Dự án",
    Work: "Công việc",
    Activity: "Hoạt động",
    Event: "Sự kiện",
    Meeting: "Cuộc họp",
    Conference: "Hội nghị",
    Workshop: "Hội thảo",
    Training: "Đào tạo",
    Education: "Giáo dục",
    Learning: "Học tập",
    Study: "Nghiên cứu",
    Research: "Nghiên cứu",
    Development: "Phát triển",
    Production: "Sản xuất",
    Manufacturing: "Sản xuất",
    Distribution: "Phân phối",
    Marketing: "Tiếp thị",
    Sales: "Bán hàng",
    Purchase: "Mua hàng",
    Buy: "Mua",
    Sell: "Bán",
    Trade: "Giao dịch",
    Exchange: "Trao đổi",
    Transfer: "Chuyển",
    Move: "Di chuyển",
    Transport: "Vận chuyển",
    Travel: "Du lịch",
    Journey: "Hành trình",
    Trip: "Chuyến đi",
    Visit: "Thăm",
    Tour: "Tour",
    Vacation: "Kỳ nghỉ",
    Holiday: "Ngày lễ",
    Weekend: "Cuối tuần",
    Today: "Hôm nay",
    Yesterday: "Hôm qua",
    Tomorrow: "Ngày mai",
    Morning: "Buổi sáng",
    Afternoon: "Buổi chiều",
    Evening: "Buổi tối",
    Night: "Đêm",
    Day: "Ngày",
    Week: "Tuần",
    Month: "Tháng",
    Year: "Năm",
    Season: "Mùa",
    Spring: "Mùa xuân",
    Summer: "Mùa hè",
    Autumn: "Mùa thu",
    Winter: "Mùa đông",
    Monday: "Thứ hai",
    Tuesday: "Thứ ba",
    Wednesday: "Thứ tư",
    Thursday: "Thứ năm",
    Friday: "Thứ sáu",
    Saturday: "Thứ bảy",
    Sunday: "Chủ nhật",
    January: "Tháng một",
    February: "Tháng hai",
    March: "Tháng ba",
    April: "Tháng tư",
    May: "Tháng năm",
    June: "Tháng sáu",
    July: "Tháng bảy",
    August: "Tháng tám",
    September: "Tháng chín",
    October: "Tháng mười",
    November: "Tháng mười một",
    December: "Tháng mười hai",
    "Save Layout": "Lưu bố cục",
    "Edit Layout": "Chỉnh sửa bố cục",
    "No widgets available": "Không có widget nào",
    Metrics: "Số liệu",
    "Order metrics": "Số liệu đơn hàng",
    "Order Count": "Số lượng đơn hàng",
    "Order Total": "Tổng đơn hàng",
    "Average Order Value": "Giá trị đơn hàng trung bình",
    "Orders Summary": "Tóm tắt đơn hàng",
    "Your orders summary": "Tóm tắt đơn hàng của bạn",
    "This Week": "Tuần này",
    "This Month": "Tháng này",
    "Total Orders": "Tổng đơn hàng",
    "Total Revenue": "Tổng doanh thu",
    "Latest Orders": "Đơn hàng mới nhất",
    "Your latest orders": "Đơn hàng mới nhất của bạn",
    "Placed At": "Đặt lúc",
    Regions: "Vùng",
    Zone: "Khu vực",
    "Translation Test": "Kiểm tra dịch thuật",
    "Current Language": "Ngôn ngữ hiện tại",
    "Direct translation": "Dịch trực tiếp",
    "Trans component": "Thành phần Trans",
    "More examples": "Thêm ví dụ",
    Roles: "Vai trò",
    Sellers: "Người bán",
    Promotions: "Khuyến mãi",
    Products: "Sản phẩm",
    Orders: "Đơn hàng",
    Facets: "Thuộc tính",
    "Delete Table": "Xóa bảng",
    "Select asset": "Chọn tài sản",
    "Filter...": "Lọc...",
    Customers: "Khách hàng",
    "Customer Groups": "Nhóm khách hàng",
    Countries: "Quốc gia",
    Collections: "Bộ sưu tập",
    Channels: "Kênh",
    Administrators: "Quản trị viên",
    "Job Queue": "Hàng đợi công việc",
    "Toggle Sidebar": "Chuyển đổi thanh bên",
    "Go to previous page": "Đi đến trang trước",
    "Go to next page": "Đi đến trang tiếp theo",
    breadcrumb: "đường dẫn",
    pagination: "phân trang",
    "https://example.com/image.jpg": "https://example.com/image.jpg",
    "https://example.com": "https://example.com",
    auto: "tự động",
    "Search assets...": "Tìm kiếm tài sản...",
    "Clear filters": "Xóa bộ lọc",
    "Asset type": "Loại tài sản",
    "All types": "Tất cả loại",
    Images: "Hình ảnh",
    Video: "Video",
    Binary: "Nhị phân",
    "Username or email address": "Tên người dùng hoặc địa chỉ email",
    Administration: "Quản trị",
    "Product Variants": "Biến thể sản phẩm",
    Assets: "Tài sản",
    // Column headers
    "Created At": "Ngày tạo",
    Data: "Dữ liệu",
    "Collection Name": "Tên bộ sưu tập",
    Contents: "Nội dung",
    "Default Language": "Ngôn ngữ mặc định",
    "Total with Tax": "Tổng có thuế",
    "Product Name": "Tên sản phẩm",
    "Variant name": "Tên biến thể",
    SKU: "SKU",
    "Unit price": "Giá đơn vị",
    // Date formats
    "just now": "vừa xong",
    "{{count}} minutes ago": "{{count}} phút trước",
    "{{count}} hours ago": "{{count}} giờ trước",
    yesterday: "hôm qua",
    "{{count}} days ago": "{{count}} ngày trước",
    // Form validation messages
    "Value cannot be empty": "Giá trị không được để trống",
    "Option name is required": "Tên tùy chọn là bắt buộc",
    "At least one value is required": "Cần ít nhất một giá trị",
    "SKU is required": "SKU là bắt buộc",
    "Price must be a positive number": "Giá phải là số dương",
    "Stock must be a non-negative integer":
      "Tồn kho phải là số nguyên không âm",
    "Please enter both start and end dates":
      "Vui lòng nhập cả ngày bắt đầu và ngày kết thúc",
    "Start date must be before end date":
      "Ngày bắt đầu phải trước ngày kết thúc",
    "At least one option value is required": "Cần ít nhất một giá trị tùy chọn",
    "At least one option group is required": "Cần ít nhất một nhóm tùy chọn",
    "Must select an option for the existing variant":
      "Phải chọn một tùy chọn cho biến thể hiện có",
    // Empty state messages
    "No checkers found": "Không tìm thấy trình kiểm tra",
    "No options found": "Không tìm thấy tùy chọn",
    "No stock locations available on current channel":
      "Không có vị trí kho nào khả dụng trên kênh hiện tại",
    "All resources are up and running":
      "Tất cả tài nguyên đang hoạt động bình thường",
    "Private collections are not visible in the shop":
      "Bộ sưu tập riêng tư không hiển thị trong cửa hàng",
    "Private facets are not visible in the shop":
      "Thuộc tính riêng tư không hiển thị trong cửa hàng",
    "Global out of stock threshold": "Ngưỡng hết hàng toàn cục",
    "The result of the job": "Kết quả của công việc",
    "Create variants for your product": "Tạo biến thể cho sản phẩm của bạn",
    "Use as the default billing address":
      "Sử dụng làm địa chỉ thanh toán mặc định",
    "Use as the default shipping address":
      "Sử dụng làm địa chỉ giao hàng mặc định",
    "Update the note content or visibility":
      "Cập nhật nội dung hoặc hiển thị ghi chú",
    "Failed to add customer to group": "Không thể thêm khách hàng vào nhóm",
    "Failed to remove customer from group":
      "Không thể xóa khách hàng khỏi nhóm",
    "Failed to update zone": "Không thể cập nhật khu vực",
    "Failed to update tax rate": "Không thể cập nhật thuế suất",
    "Failed to update tax category": "Không thể cập nhật danh mục thuế",
    "Failed to update stock location": "Không thể cập nhật vị trí kho",
    "Failed to update shipping method":
      "Không thể cập nhật phương thức vận chuyển",
    "Failed to update payment method":
      "Không thể cập nhật phương thức thanh toán",
    "Failed to update seller": "Không thể cập nhật người bán",
    "Failed to update role": "Không thể cập nhật vai trò",
    "Failed to update customer group": "Không thể cập nhật nhóm khách hàng",
    "Failed to update global settings": "Không thể cập nhật cài đặt chung",
    "Global language settings updated successfully":
      "Cài đặt ngôn ngữ toàn cục đã được cập nhật thành công",
    // Job queue states
    Running: "Đang chạy",
    Retrying: "Đang thử lại",
    Cancelled: "Đã hủy",
    // Additional column headers and UI text
    "Featured Asset": "Tài sản nổi bật",
    "Is Private": "Riêng tư",
    "Updated At": "Cập nhật lúc",
    // Selection and pagination text
    "row(s) selected": "hàng được chọn",
    "Rows per page": "Hàng mỗi trang",
    of: "của",
    // Filter and action text
    "Add filter": "Thêm bộ lọc",
    // New entity buttons
    "New Collection": "Bộ sưu tập mới",
    "New Product": "Sản phẩm mới",
    "New product": "Sản phẩm mới",
    "New Administrator": "Quản trị viên mới",
    "New Customer Group": "Nhóm khách hàng mới",
    "New Customer": "Khách hàng mới",
    "New Channel": "Kênh mới",
    "New Role": "Vai trò mới",
    "New Promotion": "Khuyến mãi mới",
    "New Stock Location": "Vị trí kho mới",
    "New Shipping Method": "Phương thức vận chuyển mới",
    "New Seller": "Người bán mới",
    "New Facet": "Thuộc tính mới",
    "New Zone": "Khu vực mới",
    "New Tax Rate": "Thuế suất mới",
    "New Tax Category": "Danh mục thuế mới",
    "New Payment Method": "Phương thức thanh toán mới",
    "New window": "Cửa sổ mới",
    // Additional UI elements
    Breadcrumbs: "Đường dẫn",
    "Parent Id": "ID Cha",
    Children: "Con",
    Columns: "Cột",
    variants: "biến thể",
    more: "nữa",
    "+ {count} more": "+ {count} nữa",
    // Order detail page translations
    "Tax summary": "Tóm tắt thuế",
    "Payment details": "Chi tiết thanh toán",
    "Order history": "Lịch sử đơn hàng",
    "No customer": "Không có khách hàng",
    "Shipping address": "Địa chỉ giao hàng",
    "Billing address": "Địa chỉ thanh toán",
    "Fulfillment details": "Chi tiết thực hiện",
    "No fulfillments": "Không có thực hiện",
    "Successfully updated order": "Cập nhật đơn hàng thành công",
    "Failed to update order": "Không thể cập nhật đơn hàng",
    "Failed to transition order to state":
      "Không thể chuyển trạng thái đơn hàng",
    "Failed to modify order": "Không thể chỉnh sửa đơn hàng",
    "Transition to": "Chuyển sang",
    "Tax rate": "Thuế suất",
    "Tax base": "Cơ sở thuế",
    "Tax total": "Tổng thuế",
    "Payment method": "Phương thức thanh toán",
    "Transaction ID": "ID Giao dịch",
    "Error message": "Thông báo lỗi",
    "Payment metadata": "Siêu dữ liệu thanh toán",
    Refunds: "Hoàn tiền",
    "Refund ID": "ID Hoàn tiền",
    Metadata: "Siêu dữ liệu",
    "Settle payment": "Thanh toán",
    "Cancel payment": "Hủy thanh toán",
    "Payment settled successfully": "Thanh toán thành công",
    "Failed to settle payment": "Không thể thanh toán",
    "Payment state updated successfully":
      "Cập nhật trạng thái thanh toán thành công",
    "Failed to update payment state":
      "Không thể cập nhật trạng thái thanh toán",
    "Payment cancelled successfully": "Hủy thanh toán thành công",
    "Failed to cancel payment": "Không thể hủy thanh toán",
    "Refund settled successfully": "Hoàn tiền thành công",
    "Failed to settle refund": "Không thể hoàn tiền",
    "Settle refund": "Hoàn tiền",
    "Fulfillment ID": "ID Thực hiện",
    "Tracking code": "Mã theo dõi",
    "Fulfilled items": "Mặt hàng đã thực hiện",
    Qty: "SL",
    "Unknown product": "Sản phẩm không xác định",
    "Fulfillment state updated successfully":
      "Cập nhật trạng thái thực hiện thành công",
    "Failed to update fulfillment state":
      "Không thể cập nhật trạng thái thực hiện",
    "No address": "Không có địa chỉ",
    Surcharge: "Phụ phí",
    "Sub total": "Tổng phụ",
    "Add payment to order": "Thêm thanh toán vào đơn hàng",
    "Add a manual payment of": "Thêm thanh toán thủ công",
    "Payment method is required": "Phương thức thanh toán là bắt buộc",
    "Search payment methods...": "Tìm kiếm phương thức thanh toán...",
    "Transaction ID is required": "ID Giao dịch là bắt buộc",
    "Enter transaction ID": "Nhập ID giao dịch",
    "Adding...": "Đang thêm...",
    "Fulfill order": "Thực hiện đơn hàng",
    "Select quantities to fulfill and configure the fulfillment handler":
      "Chọn số lượng để thực hiện và cấu hình trình xử lý thực hiện",
    "Order lines": "Dòng đơn hàng",
    "available to fulfill": "có thể thực hiện",
    "Fulfillment handler": "Trình xử lý thực hiện",
    "Fulfilling...": "Đang thực hiện...",
    "Successfully fulfilled order": "Thực hiện đơn hàng thành công",
    "Failed to fulfill order": "Không thể thực hiện đơn hàng",
    "Enter the transaction ID for this refund settlement":
      "Nhập ID giao dịch cho việc hoàn tiền này",
    "Enter transaction ID...": "Nhập ID giao dịch...",
    "Error loading order history": "Lỗi tải lịch sử đơn hàng",
    "Order not found": "Không tìm thấy đơn hàng",
    "Load more": "Tải thêm",
    From: "Từ",
    to: "đến",
    "Payment #": "Thanh toán #",
    "transitioned to": "chuyển sang",
    "Refund #": "Hoàn tiền #",
    "Fulfillment #": "Thực hiện #",
    created: "đã tạo",
    "Order modification #": "Chỉnh sửa đơn hàng #",
    "Customer information updated": "Cập nhật thông tin khách hàng",
    "Order cancelled": "Đơn hàng đã hủy",
    "Payment settled": "Thanh toán đã thanh toán",
    "Payment authorized": "Thanh toán đã ủy quyền",
    "Payment failed": "Thanh toán thất bại",
    "Payment transitioned": "Thanh toán đã chuyển",
    "Refund settled": "Hoàn tiền đã thanh toán",
    "Refund transitioned": "Hoàn tiền đã chuyển",
    "Note added": "Đã thêm ghi chú",
    "Order placed": "Đơn hàng đã đặt",
    "Order fulfilled": "Đơn hàng đã thực hiện",
    "Order shipped": "Đơn hàng đã gửi",
    "Order transitioned": "Đơn hàng đã chuyển",
    "Order delivered": "Đơn hàng đã giao",
    "Fulfillment transitioned": "Thực hiện đã chuyển",
    "Fulfillment created": "Thực hiện đã tạo",
    "Order modified": "Đơn hàng đã chỉnh sửa",
    "Customer updated": "Khách hàng đã cập nhật",
    "Seller orders": "Đơn hàng người bán",
    "Add facet values": "Thêm giá trị facet",
    "Facet values for ": "Giá trị facet cho ",
    "Facet values": "Giá trị facet",
    "Add asset": "Thêm tài nguyên",
    "When enabled, a product is available in the shop":
      "Khi được bật, sản phẩm sẽ có sẵn trong cửa hàng",
    "Insights": "Tổng quan",
    "Catalog": "Catalog",
    "Shipping Methods": "Phương thức vận chuyển",
    "Payment Methods": "Phương thức thanh toán",
    "Shipping Address": "Địa chỉ giao hàng",
    "Billing Address": "Địa chỉ thanh toán",
    "Fulfillment Details": "Chi tiết thực hiện",
    "Stock Locations": "Vị trí tồn kho",
    "Tax Categories": "Danh mục thuế",
    "Tax Rates": "Thuế suất",
    "Zones": "Khu vực",
    "Global Settings": "Cài đặt toàn cục",
    "Authorized": "Đã ủy quyền",
    "Cancel modification": "Hủy chỉnh sửa",
    "Preview changes": "Xem thay đổi",
    "Summary of modifications": "Tóm tắt các thay đổi",
    "No modifications made": "Không có thay đổi",
    "First name": "Tên",
    "Last name": "Họ",
    "Email address": "Địa chỉ email",
    "Phone number": "Số điện thoại",
    "Addresses": "Địa chỉ",
    "Default shipping": "Địa chỉ giao hàng mặc định",
    "Default billing": "Địa chỉ thanh toán mặc định",
    "Add new address": "Thêm địa chỉ mới",
    "New banner": "Banner mới",
    "List Price": "Giá gốc",
    "Original price before discounts": "Giá gốc trước khi giảm giá",
    "Starts At": "Bắt đầu lúc",
    "Ends At": "Kết thúc lúc",
  },
  en: {},
  de: {},
}

// Translation context
interface TranslationContextType {
  locale: string
  setLocale: (locale: string) => void
  t: (key: string) => string
}

const TranslationContext = createContext<TranslationContextType | undefined>(
  undefined
)

// Translation provider
export function TranslationProvider({
  children,
}: {
  children: React.ReactNode
}) {
  const [locale, setLocale] = useState("vi") // Default to Vietnamese

  const t = (key: string): string => {
    const localeTranslations = translations[locale as keyof typeof translations]
    return localeTranslations?.[key as keyof typeof localeTranslations] || key
  }

  return (
    <TranslationContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </TranslationContext.Provider>
  )
}

// Hook to use translations
export function useTranslation() {
  const context = useContext(TranslationContext)
  if (!context) {
    throw new Error("useTranslation must be used within a TranslationProvider")
  }
  return context
}

// Translation component
export function Trans({ children }: { children: string }) {
  const { t } = useTranslation()
  return <>{t(children)}</>
}

// Translation function
export function translate(key: string): string {
  const locale = "vi" // Default to Vietnamese for now
  const localeTranslations = translations[locale as keyof typeof translations]
  return localeTranslations?.[key as keyof typeof localeTranslations] || key
}
